#After Build and code quality is checked, manually merge the PR to main branch and deploy docker image

name: Merge to Main Branch

on:
  push:
    branches:
      - main


jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: set up go 1.22
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22

            - name: Build Go application
              run: |
                cd src/product-catalog
                go mod download
                go build -o product-catalog-service main.go

            - name: Install Docker
              uses: docker/setup-buildx-action@v1
              with:
                version: latest

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker image
              uses: docker/build-push-action@v2
              with:
                context: src/product-catalog
                file: src/product-catalog/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog-service:${{ github.run_id }}

    updateK8s:
            runs-on: ubuntu-latest
            needs: docker
            steps:
                - name: Checkout
                  uses: actions/checkout@v2
                  with:
                    token: ${{ secrets.GITHUB_TOKEN }}

                - name: Update Kubernetes deployment manifest
                  run: |
                    sed -i 's|image: .*|image: '${{ secrets.DOCKER_USERNAME }}/product-catalog-service:${{ github.run_id }}'|g' kubernetes/productcatalog/deploy.yaml

                - name: push kubernetes deployment manifest
                  run : |
                        git config --global user.email "aravind.chandrasekara@dal.ca" 
                        git config --global user.name "aravind-chan"
                        git add kubernetes/productcatalog/deploy.yaml
                        git commit -m "Update product catalog service image tag"
                        git push origin HEAD:main -f
                         



            

            




